name: Shipping CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run:  mvn clean install
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo npm test
        ## We will n have echo command in real world. Since this is a test application there are not test cases built.
  docker:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 624234316771.dkr.ecr.us-east-1.amazonaws.com
      - name: docker build
        run: docker build -t 624234316771.dkr.ecr.us-east-1.amazonaws.com/shipping:latest .
      - name: docker push
        run: docker push 624234316771.dkr.ecr.us-east-1.amazonaws.com/shipping:latest




